GRANT ALL ON DATABASE sem2024_matevzku TO javnost;

GRANT ALL ON SCHEMA public TO javnost;

GRANT ALL ON ALL TABLES IN SCHEMA public TO javnost;

GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO javnost;

GRANT USAGE ON SCHEMA public TO PUBLIC;

GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO javnost;

GRANT CONNECT ON DATABASE sem2024_matevzku TO javnost;